### ISSUE TITLE
bugzilla-cn-5.0.0-rc.2

### ISSUE THREAD

**Issue by zz0412** [repeat/bugzilla-tw#5]
I translation the TW language pack to simplified Chinese. Hope you can add it to the download list . Download URL:https://github.com/zz0412/svnbook/raw/master/other/bugzilla-cn-5.0.0-rc.2.zip

**Comment by repeat** [comment]
If you want to be listed on [offical Bugzilla list](https://www.bugzilla.org/download/#localizations), no, I don't have permission; you have to ask the Bugzilla team to do so.
[Bugzilla wiki](https://wiki.mozilla.org/Bugzilla:L10n:Localization_Teams) is somewhere you can put your effort on; however I suggest that you need a new repository rather than somewhere under `svnbook`.
